port: 8961
socks-port: 8962
mixed-port: 8900
redir-port: 8963
tproxy-port: 8964
ipv6: true

dns:
  enable: true
  ipv6: true
  listen: '[::]:1053'
  fake-ip-range: 198.18.0.1/16
  fake-ip-range6: fdfe:dcba:9876::1/64
  use-hosts: true
  enhanced-mode: fake-ip
  fake-ip-filter:
    - +.lan
    - +.local
    - +.rx
  respect-rules: true
  prefer-h3: true
  use-system-hosts: true
  
  default-nameserver:
    - 2001:4860:4860::8888
    - 2606:4700:4700::1111
    - 8.8.8.8
    - 1.1.1.1

  proxy-server-nameserver:
    - https://dns.google/dns-query
    - https://cloudflare-dns.com/dns-query
    
  direct-nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    
  nameserver:
    - https://dns.google/dns-query
    - https://cloudflare-dns.com/dns-query

unified-delay: true

geodata-mode: true
geodata-loader: memconservative
geox-url:
  geosite: https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat
  mmdb: https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.metadb
  geoip: https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.dat
  asn: https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/GeoLite2-ASN.mmdb